import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: ['coverage/**', 'dist/**', 'node_modules/**'],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    files: ['**/*.{js,cjs,mjs,jsx,ts,cts,mts,tsx}'],
    languageOptions: {
      parserOptions: {
        project: './tsconfig.eslint.json',
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['warn', { args: 'after-used' }],
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      'arrow-parens': ['error', 'as-needed', { requireForBlockBody: true }],
      'brace-style': ['error', '1tbs', { allowSingleLine: true }],
      'comma-dangle': ['error', 'always-multiline'],
      'comma-spacing': 'error',
      'comma-style': ['error', 'last'],
      'curly': ['error', 'multi-line'],
      'default-case': 'error',
      'dot-notation': ['error', { allowKeywords: true }],
      eqeqeq: 'error',
      'key-spacing': ['error', { beforeColon: false, afterColon: true }],
      'keyword-spacing': ['error', { after: true }],
      'no-alert': 'error',
      'no-bitwise': 'off',
      'no-console': 'off',
      'no-continue': 'error',
      'no-empty': 'error',
      'no-eval': 'error',
      'no-extend-native': 'warn',
      'no-floating-decimal': 'error',
      'no-inline-comments': 'off',
      'no-labels': 'error',
      'no-lonely-if': 'error',
      'no-multi-spaces': 'error',
      'no-multi-str': 'error',
      'no-multiple-empty-lines': ['error', { max: 2 }],
      'no-nested-ternary': 'off',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-param-reassign': ['error', { props: false }],
      'no-plusplus': 'off',
      'no-process-env': 'off',
      'no-proto': 'error',
      'no-return-assign': 'error',
      'no-script-url': 'error',
      'no-shadow': 'error',
      'no-ternary': 'off',
      'no-trailing-spaces': 'error',
      'no-undef-init': 'error',
      'no-underscore-dangle': 'off',
      'no-unused-expressions': ['error', { allowShortCircuit: true }],
      'no-var': 'error',
      'no-void': 'off',
      'object-curly-spacing': ['error', 'always'],
      'operator-linebreak': ['error', 'before'],
      'prefer-const': 'error',
      'prefer-spread': 'error',
      quotes: ['error', 'single', { avoidEscape: true }],
      semi: 'error',
      'semi-spacing': 'error',
      'space-before-blocks': ['error', 'always'],
      'space-before-function-paren': ['error', { anonymous: 'always', named: 'always' }],
      'space-in-parens': ['error', 'never'],
      'space-infix-ops': 'error',
      'space-unary-ops': ['error', { words: true, nonwords: false }],
      'use-isnan': 'error',
      'valid-typeof': 'error',
      yoda: ['error', 'never', { exceptRange: true }],
    },
  },
  {
    files: ['lib/deep-diff/**/*.ts'],
    rules: {
      'default-case': 'off',
      'no-param-reassign': 'off',
      'no-var': 'off',
      'prefer-spread': 'off',
    },
  },
);
